{
 "title": "Kafka Monitor",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Job", "query": "label_values(job)" },
   {
    "name": "Topic",
    "query": "label_values(kafka_topic_partitions{job=\"[[Job]]\"}, topic)"
   },
   {
    "name": "ConsumerGroup",
    "query": "label_values(kafka_consumergroup_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}, consumergroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "Brokers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_brokers{job=\"[[Job]]\"}"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{job=\"[[Job]]\",topic=\"[[Topic]]\"})"
    }
   ]
  },
  {
   "title": "Throughput In",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}[5m]))",
     "legendFormat": "Messages In / sec"
    }
   ]
  },
  {
   "title": "Throughput Out",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\",consumergroup=\"[[ConsumerGroup]]\"}[5m]))",
     "legendFormat": "Messages Out / sec"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"[[Topic]]\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Messages / sec" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}[5m]))",
     "legendFormat": "Partition {{partition}}"
    },
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}[5m]))",
     "legendFormat": "All partitions"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Messages / sec" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}[5m]))",
     "legendFormat": "Partition {{partition}}"
    },
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}[5m]))",
     "legendFormat": "All partitions"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ConsumerGroup Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\",consumergroup=\"[[ConsumerGroup]]\"})",
     "legendFormat": "ConsumerGroup offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"})",
     "legendFormat": "Topic offset"
    }
   ]
  }
 ]
}